config/routes.rb
Stiepgri::Application.routes.draw do
  root 'publics#home'
  get '/rekruitment',  to: 'publics#rekruitment',  as: 'rekruitment'
  get '/kontak-kami',  to: 'publics#contact_us',  as: 'contact_us'

  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register'
    }

  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_user, Startup::UserRoutes.new
  namespace :user do
    concerns :startup_user
  end

  resources :staffs
  resources :alumnis
  resources :students
  resources :user_companies
  resources :pages
  resources :news
  resources :libraries
  resources :jobs
  resources :guest_books
  resources :facilities
  resources :events
  resources :e_learnings do 
    member do 
      get 'document_download'
    end
  end
  resources :category_elearnings
  resources :downloads do 
    member do 
      get 'document_download'
    end
  end
  resources :companies
  resources :category_blogs
  resources :blogs
  resources :articles do 
    member do 
      get 'document_download'
    end
  end
  resources :categories
  resources :announcements
  resources :academic_infos
  resources :comments
  
  # namespace :user do
  #   resources :users
  #   resources :jobs
  #   resources :events
  #   resources :e_learnings
  #   resources :downloads
  #   resources :blogs
  #   resources :articles
  #   resources :announcements
  #   resources :academic_infos
  # end

end

app/models/staff.rb
class Staff < User
	extend FriendlyId
	friendly_id :username, use: [:slugged, :finders]
	
	default_scope {where(type: 'Staff')}

	include FilterUser
end

app/controllers/backend/staffs_controller.rb
class Backend::StaffsController < Backend::UsersController
	defaults resource_class: Staff, collection_name: 'staffs', instance_name: 'staff'
	include ActionMultiple

	def index
		@collection = collection.where("id != ?", current_user.id).latest.page(page).per(per_page)
	end
end

app/controllers/staffs_controller.rb
class StaffsController < ResourcesController
	defaults resource_class: Staff, collection_name: 'staffs', instance_name: 'staff'
	include Breadcrumb
	
	def index
		@collection = collection.verified.latest.page(page).per(per_page)
	end

	def show
		add_breadcrumb "#{resource.try(:profile).try(:full_name)}", resource_path
	end

	private
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/views/staffs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div id="Grid" class="masonry">
          <% @collection.each_with_index do |resource, index| %>
            <div class="col-md-3 mix" data-cat="<%= index %>">
              <div class="gallery-item">
                <%= link_to staff_path(resource) do %>
                  <div class="gallery-thumb">
                    <%= image_tag resource.try(:profile).try(:avatar).url(:medium), alt: "#{resource.username}" %>
                  </div>
                <% end %>
                <%= link_to staff_path(resource) do %>
                  <div class="gallery-content hg-title">
                    <h6 class="gallery-title">
                      <%= resource.try(:profile).try(:full_name) %>
                    </h6>
                  </div>
                <% end %>
              </div> <!-- /.gallery-item -->
            </div> <!-- /.col-md-4 -->
          <% end %>
        </div> <!-- /#Grid -->
      </div> <!-- /.row -->
      <%= paginate @collection %>
    </div> <!-- /.col-md-9 -->
    <div class="col-md-4">
      <div class="list-group margin-top30">
        <a href="#" class="list-group-item active">
          Program Studi
        </a>
        <% @study_program.each do |resource| %>
          <%= link_to page_path(resource), class: 'list-group-item' do %>
            <%= resource.title %>
          <% end %>
        <% end %>
      </div>
      <%= render 'shareds/home/form_request' %>
    </div>
  </div> <!-- /.row -->
</div> <!-- /.container -->

app/views/staffs/show.html.erb
<% @profile = resource.try(:profile) %>
<% @address = @profile.try(:address) %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-12">
          <div class="widget-item float-left full-width">
            <div class="col-md-3">
              <%= image_tag @profile.try(:avatar).url(:small), class: 'full-width' %>
            </div>
            <div class="col-md-9">
              <h4 align="center" class="margin-bottom20">
                Data Lengkap Staff Pengajar
              </h4>
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th scope="row">Nama Lengkap</th>
                    <td><%= @profile.try(:full_name) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Email</th>
                    <td>
                      <a href="mailto:<%= resource.try(:email) %>">
                        <%= resource.try(:email) %>
                      </a>
                    </td>
                  </tr>
                  <tr>
                    <th scope="row">Jenis Kelamin</th>
                    <td><%= @profile.try(:gender) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Tanggal Lahir</th>
                    <td><%= @profile.try(:birthday).strftime("%B, %d, %Y") %></td>
                  </tr>
                  <tr>
                    <th scope="row">Phone</th>
                    <td><%= @profile.try(:phone) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Alamat</th>
                    <td><%= @address.try(:address) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Kota</th>
                    <td><%= @address.try(:city) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Provinsi</th>
                    <td><%= @address.try(:province) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Kode Pos</th>
                    <td><%= @address.try(:postcode) %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="list-group margin-top30">
        <a href="#" class="list-group-item active">
          Program Studi
        </a>
        <% @study_program.each do |resource| %>
          <%= link_to page_path(resource), class: 'list-group-item' do %>
            <%= resource.title %>
          <% end %>
        <% end %>
      </div>
      <%= render 'shareds/home/form_request' %>
    </div>
  </div>
</div>