config/routes.rb
Stiepgri::Application.routes.draw do
  root 'publics#home'
  get '/rekruitment',  to: 'publics#rekruitment',  as: 'rekruitment'
  get '/kontak-kami',  to: 'publics#contact_us',  as: 'contact_us'

  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register'
    }

  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_user, Startup::UserRoutes.new
  namespace :user do
    concerns :startup_user
  end

  resources :staffs
  resources :alumnis
  resources :students
  resources :user_companies
  resources :pages
  resources :news
  resources :libraries
  resources :jobs
  resources :guest_books
  resources :facilities
  resources :events
  resources :e_learnings do 
    member do 
      get 'document_download'
    end
  end
  resources :category_elearnings
  resources :downloads do 
    member do 
      get 'document_download'
    end
  end
  resources :companies
  resources :category_blogs
  resources :blogs
  resources :articles do 
    member do 
      get 'document_download'
    end
  end
  resources :categories
  resources :announcements
  resources :academic_infos
  resources :comments
  
  # namespace :user do
  #   resources :users
  #   resources :jobs
  #   resources :events
  #   resources :e_learnings
  #   resources :downloads
  #   resources :blogs
  #   resources :articles
  #   resources :announcements
  #   resources :academic_infos
  # end

end

app/models/alumni.rb
class Alumni < User
	extend FriendlyId
	friendly_id :username, use: [:slugged, :finders]
	
	default_scope {where(type: 'Alumni')}

	include FilterUser
end

app/controllers/alumnis_controller.rb
class AlumnisController < ResourcesController
	defaults resource_class: Alumni, collection_name: 'alumnis', instance_name: 'alumni'
	include Breadcrumb
	
	def index
		@collection = collection.verified.latest.page(page).per(per_page)
	end

	def show
		add_breadcrumb "#{resource.try(:profile).try(:nim)}", resource_path
	end

	private
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/backend/alumnis_controller.rb
class Backend::AlumnisController < Backend::UsersController
	defaults resource_class: Alumni, collection_name: 'alumnis', instance_name: 'alumni'
	include ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	private
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/controllers/user/alumnis_controller.rb
class User::AlumnisController < User::UsersController
	defaults resource_class: Alumni, collection_name: 'alumnis', instance_name: 'alumni'
	include ActionMultiple

	def index
		@collection = collection.latest.page(page).per(per_page)
	end

	private
		def collection
			@collection ||= end_of_association_chain.filter_search(params)
		end
end

app/views/alumnis/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="widget-main">
        <div class="widget-main-title">
          <h4 class="widget-title">Pencarian</h4>
        </div>
        <div class="widget-inner">
          <%= form_for :search, method: 'get', url: alumnis_path do %>
            <div class="form-group">
              <label>Masukan Nama atau Nim</label>
              <% value_name = params[:name] if params[:name].present? %>
              <%= text_field_tag :name, value_name, class: "form-control", placeholder: 'Masukan Name/Nim'%>
            </div>
            <div class="form-group">
              <label>Program Studi</label>
              <% value_study_program = params[:study_program] if params[:study_program].present? %>
              <%= select_tag :study_program, options_for_select(user_program, value_study_program), prompt: 'Pilih Program Studi', class: 'searchselect form-control' %>
            </div>
            <div class="form-group">
              <label>Tahun Angkatan</label>
              <% value_generation = params[:generation] if params[:generation].present? %>
              <%= select_tag :generation, options_for_select(user_generation, value_generation), prompt: 'Pilih Tahun Angkatan', class: 'searchselect form-control' %>
            </div>
            <input class="mainBtn margin-top10" value="Submit Search" type="submit">
          <% end %>
        </div> <!-- /.widget-inner -->
      </div> <!-- /.widget-main -->
    </div> <!-- /.col-md-3 -->

    <div class="col-md-9">
      <div class="row">
        <div id="Grid" class="masonry">
          <% @collection.each_with_index do |resource, index| %>
            <div class="col-md-3 mix" data-cat="<%= index %>">
              <div class="gallery-item">
                <%= link_to alumni_path(resource) do %>
                  <div class="gallery-thumb">
                    <%= image_tag resource.try(:profile).try(:avatar).url(:medium), alt: "#{resource.username}" %>
                  </div>
                <% end %>
                <%= link_to alumni_path(resource) do %>
                  <div class="gallery-content hg-title">
                    <h6 class="gallery-title">
                      <%= resource.try(:profile).try(:nim) %>
                    </h6>
                    <p><%= resource.try(:profile).try(:full_name) %></p>
                  </div>
                <% end %>
              </div> <!-- /.gallery-item -->
            </div> <!-- /.col-md-4 -->
          <% end %>
        </div> <!-- /#Grid -->
      </div> <!-- /.row -->
      <%= paginate @collection %>
    </div> <!-- /.col-md-9 -->
  </div> <!-- /.row -->
</div> <!-- /.container -->

app/views/alumnis/show.html.erb
<% @profile = resource.try(:profile) %>
<% @address = @profile.try(:address) %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-12">
          <div class="widget-item float-left full-width">
            <div class="col-md-3">
              <%= image_tag @profile.try(:avatar).url(:small), class: 'full-width' %>
            </div>
            <div class="col-md-9">
              <h4 align="center" class="margin-bottom20">
                Data Lengkap <%= @profile.try(:nim) %>
              </h4>
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th scope="row">NIM</th>
                    <td><b><%= @profile.try(:nim) %></b></td>
                  </tr>
                  <tr>
                    <th scope="row">Nama Lengkap</th>
                    <td><%= @profile.try(:full_name) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Email</th>
                    <td>
                      <a href="mailto:<%= resource.try(:email) %>">
                        <%= resource.try(:email) %>
                      </a>
                    </td>
                  </tr>
                  <tr>
                    <th scope="row">Tahun Angkatan</th>
                    <td>Angkatan <%= @profile.try(:generation) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Program Studi</th>
                    <td><%= @profile.try(:study_program) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Jenis Kelamin</th>
                    <td><%= @profile.try(:gender) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Tanggal Lahir</th>
                    <td><%= @profile.try(:birthday).strftime("%B, %d, %Y") %></td>
                  </tr>
                  <tr>
                    <th scope="row">Phone</th>
                    <td><%= @profile.try(:phone) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Alamat</th>
                    <td><%= @address.try(:address) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Kota</th>
                    <td><%= @address.try(:city) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Provinsi</th>
                    <td><%= @address.try(:province) %></td>
                  </tr>
                  <tr>
                    <th scope="row">Kode Pos</th>
                    <td><%= @address.try(:postcode) %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="widget-main">
        <div class="widget-main-title">
          <h4 class="widget-title">Pencarian</h4>
        </div>
        <div class="widget-inner">
          <%= form_for :search, method: 'get', url: alumnis_path do %>
            <div class="form-group">
              <label>Masukan Nama atau Nim</label>
              <% value_name = params[:name] if params[:name].present? %>
              <%= text_field_tag :name, value_name, class: "form-control", placeholder: 'Masukan Name/Nim'%>
            </div>
            <div class="form-group">
              <label>Program Studi</label>
              <% value_study_program = params[:study_program] if params[:study_program].present? %>
              <%= select_tag :study_program, options_for_select(user_program, value_study_program), prompt: 'Pilih Program Studi', class: 'searchselect form-control' %>
            </div>
            <div class="form-group">
              <label>Tahun Angkatan</label>
              <% value_generation = params[:generation] if params[:generation].present? %>
              <%= select_tag :generation, options_for_select(user_generation, value_generation), prompt: 'Pilih Tahun Angkatan', class: 'searchselect form-control' %>
            </div>
            <input class="mainBtn margin-top10" value="Submit Search" type="submit">
          <% end %>
        </div> <!-- /.widget-inner -->
      </div> <!-- /.widget-main -->
    </div>
  </div>
</div>