config/routes.rb
Stiepgri::Application.routes.draw do
  root 'publics#home'
  get '/rekruitment',  to: 'publics#rekruitment',  as: 'rekruitment'
  get '/kontak-kami',  to: 'publics#contact_us',  as: 'contact_us'

  devise_for :users, 
    controllers: { 
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    }, 
    path_names: { 
      sign_in:  'login', 
      sign_out: 'logout', 
      sign_up:  'register'
    }

  concern :startup_backend, Startup::BackendRoutes.new
  namespace :backend do
    concerns :startup_backend
  end

  concern :startup_user, Startup::UserRoutes.new
  namespace :user do
    concerns :startup_user
  end

  resources :staffs
  resources :alumnis
  resources :students
  resources :user_companies
  resources :pages
  resources :news
  resources :libraries
  resources :jobs
  resources :guest_books
  resources :facilities
  resources :events
  resources :e_learnings do 
    member do 
      get 'document_download'
    end
  end
  resources :category_elearnings
  resources :downloads do 
    member do 
      get 'document_download'
    end
  end
  resources :companies
  resources :category_blogs
  resources :blogs
  resources :articles do 
    member do 
      get 'document_download'
    end
  end
  resources :categories
  resources :announcements
  resources :academic_infos
  resources :comments
  
  # namespace :user do
  #   resources :users
  #   resources :jobs
  #   resources :events
  #   resources :e_learnings
  #   resources :downloads
  #   resources :blogs
  #   resources :articles
  #   resources :announcements
  #   resources :academic_infos
  # end

end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ResourcesController
	layout 'backend'
	before_filter :authenticate_admin!
	protect_from_forgery with: :exception
	
	def beranda
	end

	def authenticate_admin!
  	unless current_user.present? && (current_user.admin?) || current_user.present? && (current_user.staff?)
      redirect_to root_path 
    end 
  end

end

app/controllers/user/home_controller.rb
class User::HomeController < User::ResourcesController
	layout 'user'
	before_filter :authenticate_admin!
	protect_from_forgery with: :exception
	
	def beranda
	end

	def authenticate_admin!
  	unless current_user.present? && (current_user.student?) || current_user.present? && (current_user.alumni?) || current_user.present? && (current_user.company?)
      redirect_to root_path 
    end 
  end

end

app/views/shareds/home/_form_request.html.erb
<div class="widget-item">
  <div class="request-information">
    <h4 class="widget-title">Buku Tamu</h4>
    <%= form_for GuestBook.new, method: 'post', url: guest_books_path, html: {class: 'request-info clearfix'} do |f| %>
      <div class="full-row">
        <label for="yourname">Nama:</label>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="full-row">
        <label for="email-id">Alamat Email:</label>
        <%= f.email_field :email, required: true %>
      </div>
      <div class="full-row">
        <label for="email-id">Pesan:</label>
        <%= f.text_area :message, class: 'form-control', style: 'height: 105px;' %>
      </div>
      <div class="full-row">
        <%= recaptcha_tags %>
      </div>
      <div class="full-row">
        <div class="submit_field">
          <span class="small-text pull-left"></span>
          <input class="mainBtn pull-right" type="submit" name="" value="Kirim Pesan" />
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shareds/home/_latest_academic.html.erb
<div class="widget-main">
  <div class="widget-main-title">
    <h4 class="widget-title">
      Informasi Akademik
      <%= link_to 'More', academic_infos_path, class: 'float-right' %>
    </h4>
  </div> <!-- /.widget-main-title -->
  <div class="widget-inner <%= 'height400' if params[:action] == 'home' %>">
    <% @latest_academic.each do |resource| %>
      <div class="blog-list-post clearfix">
        <div class="blog-list-details">
          <h5 class="blog-list-title">
            <%= link_to academic_info_path(resource) do %>
              <%= resource.title %>
            <% end %>
          </h5>
          <p class="blog-list-meta small-text">
            <i class="fa fa-calendar-o"></i>
            <span class="grey">
              <%= resource.try(:created_at).strftime("%H:%M %B, %d, %Y") %>
            </span>
            <i class="fa fa-eye"></i>
            <span class="grey">
              <%= resource.impressionist_count %> orang melihat ini
            </span>
          </p>
        </div>
      </div> <!-- /.blog-list-post -->
    <% end %>
  </div>
</div>

app/views/shareds/home/_latest_events.html.erb
<div class="widget-main">
  <div class="widget-main-title">
    <h4 class="widget-title">
      Events
      <%= link_to 'More', events_path, class: 'float-right' %>
    </h4>
  </div> <!-- /.widget-main-title -->
  <div class="widget-inner <%= 'height400' if params[:action] == 'home' %>">
    <% @events.each do |resource| %>
      <div class="event-small-list clearfix">
        <div class="calendar-small">
          <span class="s-month">
            <%= resource.try(:created_at).strftime("%B") if resource.created_at %>
          </span>
          <span class="s-date">
            <%= resource.try(:event_at).strftime("%d") if resource.event_at %>
          </span>
        </div>
        <div class="event-small-details">
          <h5 class="event-small-title">
            <%= link_to event_path(resource) do %>
              <%= resource.title %>
            <% end %>
          </h5>
          <p class="event-small-meta small-text">
            Lokasi : <%= resource.place %>
          </p>
        </div>
      </div>
    <% end %>
  </div> <!-- /.widget-inner -->
</div>

app/views/shareds/home/_our_gallery.html.erb
<div class="widget-main">
  <div class="widget-main-title">
    <h4 class="widget-title">Galleri Foto</h4>
  </div>
  <div class="widget-inner">
    <div class="gallery-small-thumbs clearfix">
      <% @galleries.each do |resource| %>
        <div class="thumb-small-gallery">
          <a class="fancybox" rel="gallery1" href="<%= resource.file.url %>" title="<%= resource.title %>">
            <%= image_tag resource.file.url(:thumb) %>
          </a>
        </div>
      <% end %>
    </div> <!-- /.galler-small-thumbs -->
  </div> <!-- /.widget-inner -->
</div>

app/views/shareds/home/_our_prodi.html.erb
<div class="col-md-12">
  <div class="widget-main">
    <div class="widget-inner">
      <div class="our-campus clearfix">
        <ul class="row">
          <% @supporteds.each do |resource| %>
            <li class="col-md-3 col-xs-3">
              <a href="<%= resource.link_url %>">
                <%= image_tag resource.file.url(:medium), class: 'full-width' %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div> <!-- /.widget-main -->
</div>

app/views/shareds/home/_our_side_right_info.html.erb
<div class="widget-main">
  <div class="widget-main-title">
    <h4 class="widget-title">
      Info Terbaru
      <%= link_to 'More', news_index_path, class: 'float-right' %>
    </h4>
  </div>
  <div class="widget-inner">
    <% @latest_news.each do |resource| %>
      <div class="prof-list-item clearfix">
        <div class="prof-thumb">
          <%= image_tag resource.file.url(:medium) %>       
        </div>
        <div class="prof-details">
          <%= link_to news_path(resource) do %>
            <h5 class="prof-name-list"><%= resource.title %></h5>
          <% end %>
          <p class="small-text">
            <%= truncate(strip_tags(resource.description.to_s), length: 80, omission: ' ...') %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shareds/home/_our_testimonial.html.erb
<div class="widget-main">
  <div class="widget-main-title">
    <h4 class="widget-title">Pengumuman</h4>
  </div>
  <div class="widget-inner">
    <div id="slider-testimonials">
      <ul>
        <% @announcements.each do |resource| %>
          <li>
            <p>
              <%= resource.description.html_safe if resource.description.present? %>
              <strong class="dark-text"><%= resource.try(:user).try(:username) %></strong>
            </p>
          </li>
        <% end %>
      </ul>
      <a class="prev fa fa-angle-left" href="./index.html"></a>
      <a class="next fa fa-angle-right" href="./index.html"></a>
    </div>
  </div>
</div>

app/views/shareds/home/_slide_news.html.erb
<div class="col-md-12">
  <div class="main-slideshow">
    <div class="flexslider">
      <ul class="slides">
        <% @setting.galleries.latest.each do |resource| %>
          <li>
            <%= image_tag resource.file.url(:medium) %>
            <div class="slider-caption">
              <h2><a href="#"><%= resource.title %></a></h2>
              <p><%= resource.description %></p>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>